### ISSUE TITLE
[AC-16] Account input

### ISSUE THREAD

**Issue by detlog** [sw21-tug/Team_08#20]
**User Story**
As an application user i want to login into the application to access more features.

**Acceptance Criteria**  
* Settings screen with username and password are added to the navigation
* User can enter his data
* ~~backend receives authentication request~~
 
**Technical Specifications**
for mockup see [Settings Screen ](https://github.com/sw21-tug/Team_08/wiki/Settings-Screen)

**Dependencies**
is blocked by [AC-15](https://github.com/sw21-tug/Team_08/issues/19)

**Comment by stefblue** [comment]
No saving of data, no integration with backend
